version: '2'
services:


  jenkins:
    #build: jenkins
    image: jenkins/jenkins
    container_name: sockyjam.jenkins.java
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /etc/localtime:/etc/localtime
    ports:
      - "8080:8080"
      - "50000:50000"




